# Generated by Django 4.1.2 on 2022-10-26 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.TextField(blank=True, null=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('Country', models.TextField(blank=True, null=True)),
                ('RoleType', models.IntegerField(default=0)),
                ('RoleName', models.TextField(default='Admin')),
                ('Creation_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Deletion_Time', models.DateTimeField(blank=True, default=None, null=True)),
                ('profilePic', models.TextField(blank=True, default=None, null=True)),
                ('isDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('isVerified', models.BooleanField(blank=True, default=False, null=True)),
                ('isSocial', models.BooleanField(blank=True, default=False, null=True)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
