# Generated by Django 4.1.2 on 2022-10-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_Gift_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.TextField(blank=True, default='English', null=True),
        ),
    ]
