# Generated by Django 4.1.2 on 2022-10-27 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_Gift_app', '0002_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingProfile',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.TextField(blank=True, null=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('PhoneNumber', models.TextField(blank=True, null=True)),
                ('Country', models.TextField(blank=True, null=True)),
                ('Creation_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Deletion_Time', models.DateTimeField(blank=True, default=None, null=True)),
                ('profilePic', models.TextField(blank=True, default=None, null=True)),
                ('isDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(default=0)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
