# Generated by Django 4.1.2 on 2022-10-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_Gift_app', '0004_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWallet',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.TextField(blank=True, default='', null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
