# Generated by Django 4.1.2 on 2022-10-28 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_Gift_app', '0006_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendReceiveCards',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('receiverPhone', models.TextField(blank=True, default='', null=True)),
                ('isClaimed', models.BooleanField(default=False)),
                ('cardPic', models.TextField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('recieverName', models.TextField(blank=True, default='', null=True)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('isDeleted', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_Gift_app.cards')),
                ('senderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
