# Generated by Django 4.1.2 on 2022-10-28 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_Gift_app', '0007_sendreceivecards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_to', models.TextField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('read', models.BooleanField(default=False)),
                ('unread', models.BooleanField(default=True)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('isDeleted', models.BooleanField(default=False)),
                ('notification_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
