# Generated by Django 4.1.2 on 2022-10-28 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_Gift_app', '0009_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('phoneNumber', models.TextField(blank=True, default='', null=True)),
                ('message', models.TextField(blank=True, default='', null=True)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
